### ISSUE TITLE
cannot connect to the band

### ISSUE THREAD

**Issue by zly9844** [jashgopani/mibandsdk#3]
Thanks for your job!
I build an apk from your project and install it on my phone, i can find the band mac.
But when i click on the "CONNECT BAND" button, nothing happens but just a message saying "Connecting..." and  that's all,
there's nothing on the screen and i cannot do anything.
My band is miband 4.
Thank you again!

**Comment by jashgopani** [comment]
Thanks for trying this out. Unfortunately, at this moment, sdk only works with miband 1. The Auth mechanism in the later versions of mibands is different...so that part is yet to be added.
